export const SET_VIEW_MODE = "SET_VIEW_MODE";
export const LOADING = "LOADING";
export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";
export const SEARCH = "SEARCH";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";